#!/bin/sh

if [ -f ~/.bashrc ]
then
	. ~/.bashrc
fi
if [ -f ~/.bash_aliases ]
then
	. ~/.bash_aliases
fi

# PHP 7.1
PATH="/usr/local/opt/php@7.1/bin:${PATH}"
PATH="/usr/local/opt/php@7.1/sbin:${PATH}"
export PATH
